#!/usr/bin/env bash

telegram(){
    result="$(curl -s -X POST "https://api.telegram.org/bot${TEL_API_TOKEN}/sendMessage" -d chat_id=${TEL_API_ID} -d text="New ip is ${new_ip}")"
    echo "Telegram warning sent"
}

godaddy(){
    curl -s -X PUT "https://api.godaddy.com/v1/domains/${GD_DOMAIN}/records/${GD_RECORD_TYPE}/${GD_RECORD_NAME}" \
	    -H "Authorization: sso-key ${GD_API_KEY}:${GD_API_SECRET}" \
	    -H "Content-Type: application/json" \
	    -d "[{\"data\": \"${new_ip}\"}]"
	echo "GoDaddy record updated"
}

main(){
    if [ "$(whoami)" != "root" ]; then
        echo "This program should be executed as root. Exiting"
        exit 1
    fi
    new_ip="$(curl -s icanhazip.com)"
    
    source /etc/ipwarn.conf
    if [ "${new_ip}" != "${IP}" ]; then
        sed -i -e 's/IP="'"${IP}"'"/IP="'"${new_ip}"'"/g' /etc/ipwarn.conf
        echo "New ip is ${new_ip}"
        while [ $# -gt 0 ]; do
            case "$1" in
                -t|--telegram)
                    telegram
                    shift
                    ;;
                -g|--godaddy)
                    godaddy
                    shift
                    ;;
                *)
                    break
                    ;;
            esac
        done
    fi
}

main "$@"
